name: Build Minecraft Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build inside AdminMod folder
        run: |
          cd AdminMod
          gradle wrapper --gradle-version 8.10
          chmod +x gradlew
          ./gradlew build

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdminMod-Jar
          path: AdminMod/build/libs/*.jar
